version: '3.5'
services:
  tracker:
    image: ygqygq2/fastdfs-nginx
    container_name: tracker
    volumes:
      # let container use same timezone as host
      # - '/etc/localtime:/etc/localtime'
      - './Shanghai:/etc/localtime:ro'
      - './tracker:/var/fdfs'
    command: tracker
    ports:
      - '22122:22122'
    networks:
      fastdfs:
        ipv4_address: 172.21.0.110
  storage:
    image: ygqygq2/fastdfs-nginx
    container_name: storage
    volumes:
      # - '/etc/localtime:/etc/localtime'
      - './Shanghai:/etc/localtime:ro'
      - './storage:/var/fdfs'
      - './nginx/conf:/usr/local/nginx/conf/conf.d'
      - './nginx/logs:/usr/local/nginx/logs'
    environment:
      TRACKER_SERVER: 'tracker:22122'
    ports:
      - '23000:23000'
      - '8888:8080'
    depends_on:
      - tracker
    command: storage
    networks:
      fastdfs:
        ipv4_address: 172.21.0.120

networks:
  fastdfs:
    name: fastdfs   # 避免生成网络的名称包含项目前缀
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
